version: '3.8'

services:
  mongo:
    container_name: training
    image: mongo:latest
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    
    networks:
      - training_network

networks:
  training_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local